Repository asmeurer/removestar, pull requests merged in 2023-09, with the labels that each got.

#34 Rearrange directories + minor CI updates
  .github/workflows/main.yml
  tests/__init__.py
  tests/test_removestar.py
Labels: refactor

#36 Enable pre-commit
  .git-blame-ignore-revs
  .github/workflows/main.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  _config.yml
  pyproject.toml
  removestar/__main__.py
  removestar/helper.py
  removestar/removestar.py
  tests/test_removestar.py
Labels: enhancement

#37 Revamp CI-CD pipeline
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  README.md
Labels: enhancement

#38 Add .git_archival.txt and .gitattributes
  .git_archival.txt
  .gitattributes
  .github/workflows/ci.yml
  README.md
Labels: enhancement

#40 Create a pre-commit hook
  .pre-commit-hooks.yaml
  README.md
  removestar/__main__.py
  tests/test_removestar.py
Labels: enhancement

#41 Colored output
  removestar/__main__.py
  removestar/output.py
  removestar/removestar.py
  tests/test_removestar.py
Labels: enhancement

#42 Use trusted publisher deployment
  .github/workflows/cd.yml
Labels: enhancement, ci/cd

#31 Compatibility with jupyter notebooks
  .github/workflows/ci.yml
  README.md
  pyproject.toml
  removestar/__main__.py
  removestar/removestar.py
  tests/test_removestar_nb.py
Labels: enhancement
